### ISSUE TITLE
Pitest gradle plugin doesn't work with descartes

### ISSUE THREAD

**Issue by MaelAudren** [STAMP-project/pitest-descartes#81]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**:  block
- **Tool/Service/Component**: gradle-pitest-plugin:1.3.0, descartes:1.2, gradle 2.10 and 4.10.2
- **Execution Environment**: linux
- **Reporter**: mael.audren@activeeon.com

#### Description

Using Descartes fail with the gradle plugin. Here is the stack trace:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/pitest/functional/predicate/Predicate
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: org.pitest.functional.predicate.Predicate
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
:pitest FAILED
```
 
#### Steps to reproduce the bug with gradle 2.10

Clone the repository:
`git clone https://github.com/MaelAudren/catalog.git`

Go into the repository and select the 'descartes' branch:
```
cd catalog
git checkout descartes
```

Launch pitest command with gradle:
`./gradlew pitest`

#### Step to have a working pitest without descartes
The commit before HEAD is a working pitest configuration without descartes, you can reset to this config with:
`git reset --hard HEAD~1` or `git reset --hard f9b075b`
then test it with:
`./gradlew pitest`

**Comment by oscarlvp** [comment]
This was a version issue.
The gradle plugin have encoded a default version of PIT (currently prior to 1.4.0). If a different version is specified, then it will use the PIT core with that version but PIT's command line tool will be still executed with the previous version.
The workaround is to set the desired PIT version with the `pitestVersion` property.
The `README.md` file has been modified to reflect this.
