### ISSUE TITLE
RuntimeException while transforming class when running on JDK 11

### ISSUE THREAD

**Issue by rubenlop88** [STAMP-project/pitest-descartes#92]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: minor
- **Tool/Service/Component**: Pitest Descartes 1.2.4, Pitest 1.4.0
- **Execution Environment**: macOS
- **Reporter**: Ruben Lopez, rubenlop88@gmail.com

#### Description
```
RuntimeException while transforming  com/vangle/zen/Node

java.lang.IllegalArgumentException: Unsupported class file major version 55
      at org.pitest.reloc.asm.ClassReader.<init>(ClassReader.java:166)
      at org.pitest.reloc.asm.ClassReader.<init>(ClassReader.java:148)
      at org.pitest.reloc.asm.ClassReader.<init>(ClassReader.java:136)
      at org.pitest.classinfo.ComputeClassWriter.typeInfo(ComputeClassWriter.java:192)
      at org.pitest.classinfo.ComputeClassWriter.getCommonSuperClass(ComputeClassWriter.java:71)
      at org.pitest.reloc.asm.SymbolTable.addMergedType(SymbolTable.java:1157)
      at org.pitest.reloc.asm.Frame.merge(Frame.java:1290)
      at org.pitest.reloc.asm.Frame.merge(Frame.java:1235)
      at org.pitest.reloc.asm.MethodWriter.computeAllFrames(MethodWriter.java:1575)
      at org.pitest.reloc.asm.MethodWriter.visitMaxs(MethodWriter.java:1513)
      at org.pitest.coverage.analysis.AbstractCoverageStrategy.visitMaxs(AbstractCoverageStrategy.java:71)
      at org.pitest.reloc.asm.MethodVisitor.visitMaxs(MethodVisitor.java:762)
      at org.pitest.reloc.asm.tree.MethodNode.accept(MethodNode.java:795)
      at org.pitest.coverage.analysis.CoverageAnalyser.visitEnd(CoverageAnalyser.java:63)
      at org.pitest.reloc.asm.ClassReader.readMethod(ClassReader.java:1242)
      at org.pitest.reloc.asm.ClassReader.accept(ClassReader.java:631)
      at org.pitest.reloc.asm.ClassReader.accept(ClassReader.java:355)
      at org.pitest.coverage.CoverageTransformer.transformBytes(CoverageTransformer.java:54)
      at org.pitest.coverage.CoverageTransformer.transform(CoverageTransformer.java:35)
      at java.instrument/java.lang.instrument.ClassFileTransformer.transform(ClassFileTransformer.java:246)
      at java.instrument/sun.instrument.TransformerManager.transform(TransformerManager.java:188)
      at java.instrument/sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:563)
      at java.base/java.lang.ClassLoader.defineClass1(Native Method)
      at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
      at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
      at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
      at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
      at java.base/java.lang.ClassLoader.defineClass1(Native Method)
      at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
      at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
      at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
      at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
      at java.base/java.lang.ClassLoader.defineClass1(Native Method)
      at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
      at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
      at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
      at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
      at java.base/java.lang.ClassLoader.defineClass1(Native Method)
      at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
      at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
      at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
      at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
      at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
      at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
      at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
      at java.base/java.lang.Class.forName0(Native Method)
      at java.base/java.lang.Class.forName(Class.java:398)
      at org.pitest.classinfo.ClassName.lambda$nameToClass$1(ClassName.java:108)
      at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
      at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
      at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
      at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
      at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
      at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
      at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
      at org.pitest.coverage.execute.CoverageMinion.discoverTests(CoverageMinion.java:157)
      at org.pitest.coverage.execute.CoverageMinion.getTestsFromParent(CoverageMinion.java:138)
      at org.pitest.coverage.execute.CoverageMinion.ma
```
#### Steps to reproduce

I don't know exactly what I have in this particular class that triggers the error. All the other classes work just fine.

**Comment by oscarlvp** [comment]
I have never used the tool with a JDK 11 project. Is it possible to have a pointer to the project under analysis?

**Comment by oscarlvp** [comment]
#122 solved this issue
